# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

# trigger:
# - master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.101'

- script: |
    dotnet tool install -g GitVersion.Tool --version 4.0.1-beta1-58
  displayName: 'Install global tools'

- script: dotnet-gitversion /output buildserver
  displayName: 'Run GitVersion.Tool'

# - bash: printenv | sort
#   displayName: 'List environment variables'

- task: DotNetCoreCLI@2
  displayName: 'Build source'
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- powershell: |
    $testAssemblies = Get-ChildItem -Path '$(Build.SourcesDirectory)' -Recurse -File -Filter '*.Tests.csproj' | Select-Object -ExpandProperty BaseName
    Write-Output "##vso[task.setvariable variable=testAssemblies]$($testAssemblies -join '|')"
  displayName: 'Set test assembly filter variable'

- task: DotNetCoreCLI@2
  displayName: 'Run tests with coverage'
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) /p:AltCover=true /p:AltCoverOpenCover=true /p:AltCoverAssemblyExcludeFilter="xunit|$(testAssemblies)"'

- powershell: |
    $coverageFile = Get-ChildItem -Path '$(Build.SourcesDirectory)' -Recurse -File -Filter 'coverage.xml' | Select-Object -First 1
    & "$ENV:USERPROFILE\.nuget\packages\codecov\1.1.0\tools\codecov.exe" -f "$($coverageFile.FullName)" -t '$(CODECOV_TOKEN)'
  displayName: 'Upload coverage to codecov.io'
